//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomNumbersWinFormsClient.RandomNumbersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RandomNumbersService.IRandomNumbersService", CallbackContract=typeof(RandomNumbersWinFormsClient.RandomNumbersService.IRandomNumbersServiceCallback))]
    public interface IRandomNumbersService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRandomNumbersService/GenerateRandomNumbers")]
        void GenerateRandomNumbers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRandomNumbersService/GenerateRandomNumbers")]
        System.Threading.Tasks.Task GenerateRandomNumbersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/get_StartStopFlag", ReplyAction="http://tempuri.org/IRandomNumbersService/get_StartStopFlagResponse")]
        bool get_StartStopFlag();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/get_StartStopFlag", ReplyAction="http://tempuri.org/IRandomNumbersService/get_StartStopFlagResponse")]
        System.Threading.Tasks.Task<bool> get_StartStopFlagAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/set_StartStopFlag", ReplyAction="http://tempuri.org/IRandomNumbersService/set_StartStopFlagResponse")]
        void set_StartStopFlag(bool value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/set_StartStopFlag", ReplyAction="http://tempuri.org/IRandomNumbersService/set_StartStopFlagResponse")]
        System.Threading.Tasks.Task set_StartStopFlagAsync(bool value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/VerifyUserNameAndPassword", ReplyAction="http://tempuri.org/IRandomNumbersService/VerifyUserNameAndPasswordResponse")]
        bool VerifyUserNameAndPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/VerifyUserNameAndPassword", ReplyAction="http://tempuri.org/IRandomNumbersService/VerifyUserNameAndPasswordResponse")]
        System.Threading.Tasks.Task<bool> VerifyUserNameAndPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/PingServer", ReplyAction="http://tempuri.org/IRandomNumbersService/PingServerResponse")]
        bool PingServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbersService/PingServer", ReplyAction="http://tempuri.org/IRandomNumbersService/PingServerResponse")]
        System.Threading.Tasks.Task<bool> PingServerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRandomNumbersServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRandomNumbersService/CallRecieveStreamingNumbersMsg")]
        void CallRecieveStreamingNumbersMsg(string StreamingNumbersMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRandomNumbersServiceChannel : RandomNumbersWinFormsClient.RandomNumbersService.IRandomNumbersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RandomNumbersServiceClient : System.ServiceModel.DuplexClientBase<RandomNumbersWinFormsClient.RandomNumbersService.IRandomNumbersService>, RandomNumbersWinFormsClient.RandomNumbersService.IRandomNumbersService {
        
        public RandomNumbersServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RandomNumbersServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RandomNumbersServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RandomNumbersServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RandomNumbersServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GenerateRandomNumbers() {
            base.Channel.GenerateRandomNumbers();
        }
        
        public System.Threading.Tasks.Task GenerateRandomNumbersAsync() {
            return base.Channel.GenerateRandomNumbersAsync();
        }
        
        public bool get_StartStopFlag() {
            return base.Channel.get_StartStopFlag();
        }
        
        public System.Threading.Tasks.Task<bool> get_StartStopFlagAsync() {
            return base.Channel.get_StartStopFlagAsync();
        }
        
        public void set_StartStopFlag(bool value) {
            base.Channel.set_StartStopFlag(value);
        }
        
        public System.Threading.Tasks.Task set_StartStopFlagAsync(bool value) {
            return base.Channel.set_StartStopFlagAsync(value);
        }
        
        public bool VerifyUserNameAndPassword(string username, string password) {
            return base.Channel.VerifyUserNameAndPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyUserNameAndPasswordAsync(string username, string password) {
            return base.Channel.VerifyUserNameAndPasswordAsync(username, password);
        }
        
        public bool PingServer() {
            return base.Channel.PingServer();
        }
        
        public System.Threading.Tasks.Task<bool> PingServerAsync() {
            return base.Channel.PingServerAsync();
        }
    }
}
